name: Publish to PyPI

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags, e.g., v1.0

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'  # Use your desired Python version

    - name: Extract version from tag
      id: extract_version
      run: echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

    # - name: Update package version
    #   run: |
    #     sed -i "s/^version = .*/version = '${{ env.version }}'/" setup.py

    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install setuptools build twine

    - name: Build package
      run: python -m build

    - name: Publish to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
      run: python -m twine upload dist/*
